// People pages: output/people/<name>.md per person, aggregating their action
// items and shared meetings from the recorder's notes. Deterministic — every
// rebuild scans all meeting notes and regenerates the pages, so there's no
// dedup state to corrupt. Runs after each meeting-note write.

import { api } from "../api";
import { actionOwner, myNames, noteTranscript, parseMeetingNote } from "./meetingRec";
import { getSettings } from "./settings";

interface PersonData {
  name: string; // display casing from first sighting
  actions: Array<{ text: string; note: string; date: string }>;
  meetings: Array<{ note: string; title: string; date: string }>;
}

function slug(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "person"
  );
}

/** A usable person name: 1-3 words, not me, not an unrenamed "Speaker N",
 * not a joint/team owner ("Alex/team", "Sam & Taylor"). */
function validName(name: string, me: string[]): boolean {
  const n = name.trim();
  if (!n || n.length > 30 || n.split(/\s+/).length > 3) return false;
  if (/^speaker \d+$/i.test(n) || /[/&,+]/.test(n)) return false;
  const lower = n.toLowerCase();
  return !me.some((m) => lower === m || lower.split(/\s+/).includes(m));
}

/** Scan all meeting notes and regenerate every people page. Returns the
 * number of pages written. Callers git-sync afterwards. */
export async function rebuildPeoplePages(vaultDir: string): Promise<number> {
  const files = await api.listVault(vaultDir);
  const notes = files.filter((d) =>
    d.name.toLowerCase().replace(/\\/g, "/").includes("output/meetings/")
  );
  const me = myNames();
  const people = new Map<string, PersonData>();
  const get = (raw: string): PersonData | null => {
    if (!validName(raw, me)) return null;
    const key = raw.trim().toLowerCase();
    let p = people.get(key);
    if (!p) {
      p = { name: raw.trim(), actions: [], meetings: [] };
      people.set(key, p);
    }
    return p;
  };

  for (const d of notes) {
    let md: string;
    try {
      md = await api.readVaultFile(vaultDir, d.path);
    } catch {
      continue;
    }
    const parts = parseMeetingNote(md);
    const base = d.name.split(/[\\/]/).pop()?.replace(/\.md$/, "") ?? d.name;
    const date = (parts.date ?? "").slice(0, 10);
    const attendees = new Map<string, string>(); // lower → display casing

    for (const a of parts.actions) {
      const owner = actionOwner(a);
      if (!owner) continue;
      const p = get(owner);
      if (!p) continue;
      p.actions.push({ text: a, note: base, date });
      attendees.set(owner.trim().toLowerCase(), owner.trim());
    }
    // Renamed speakers ("**Jen:** …") in the transcript count as attendees;
    // validName drops un-renamed "Speaker N" and me. Scanned only in the
    // transcript section so bold labels in AI summaries don't become people.
    for (const m of noteTranscript(md).matchAll(/^\*\*([^*\n]{2,30}):\*\*/gm)) {
      attendees.set(m[1].trim().toLowerCase(), m[1].trim());
    }

    for (const display of attendees.values()) {
      const p = get(display);
      if (!p) continue;
      if (!p.meetings.some((mm) => mm.note === base)) {
        p.meetings.push({ note: base, title: parts.title, date });
      }
    }
  }

  let written = 0;
  for (const p of people.values()) {
    if (p.actions.length === 0 && p.meetings.length < 1) continue;
    const newestFirst = <T extends { date: string }>(arr: T[]) =>
      [...arr].sort((a, b) => b.date.localeCompare(a.date));
    const lines = [
      "---",
      `title: ${p.name}`,
      "type: person",
      `updated: ${new Date().toISOString()}`,
      "---",
      "",
      `# ${p.name}`,
      "",
      "## Action items",
      "",
      ...(p.actions.length
        ? newestFirst(p.actions).map((a) => `- ${a.text} — [[${a.note}]]${a.date ? ` (${a.date})` : ""}`)
        : ["- none recorded"]),
      "",
      "## Meetings",
      "",
      ...(p.meetings.length
        ? newestFirst(p.meetings).map((m) => `- [[${m.note}]] — ${m.title}${m.date ? ` (${m.date})` : ""}`)
        : ["- none recorded"]),
      "",
      "> Generated by cipherManager from meeting notes — edits here are overwritten.",
      "",
    ].join("\n");
    await api.writeVaultFile(vaultDir, `output/people/${slug(p.name)}.md`, lines);
    written++;
  }
  return written;
}

/** People pages whose name appears in the given text (e.g. a meeting title). */
export async function matchingPeoplePages(
  text: string
): Promise<Array<{ name: string; rel: string }>> {
  const vaultDir = getSettings().vaultDir.trim();
  if (!vaultDir) return [];
  try {
    const files = await api.listVault(vaultDir);
    const lower = text.toLowerCase();
    return files
      .filter((d) => d.name.toLowerCase().replace(/\\/g, "/").includes("output/people/"))
      .map((d) => ({
        name: (d.name.split(/[\\/]/).pop() ?? "").replace(/\.md$/, "").replace(/-/g, " "),
        rel: d.name,
      }))
      .filter((p) => p.name.split(" ").some((w) => w.length > 2 && lower.includes(w)));
  } catch {
    return [];
  }
}
