//! Memory Contract Doctor (second-brain slice 2). Deterministic, AI-free:
//! reads the vault's routing contract (CLAUDE.md/AGENTS.md), compares
//! documented routes against the real folder layout, reports drift, and
//! proposes a markdown patch. Never writes anything itself — the frontend
//! applies the patch through write_vault_file after a visible preview.

use std::collections::BTreeSet;
use std::path::Path;

#[derive(serde::Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct DoctorFinding {
    pub kind: String, // "no-contract" | "undocumented-folder" | "dead-route" | "missing-destination" | "conflict" | "no-generated-rule"
    pub detail: String,
}

#[derive(serde::Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct DoctorReport {
    pub contract_rel: Option<String>, // "CLAUDE.md" | "AGENTS.md" | None
    pub findings: Vec<DoctorFinding>,
    pub patch: Option<String>, // markdown to append (or the full new CLAUDE.md when contract_rel is None)
    pub healthy: bool,         // findings.is_empty()
}

/// Destinations every second-brain vault needs a stated home for.
const CATEGORIES: &[&str] = &["meetings", "briefs", "decisions", "projects", "people", "memory"];

/// Purpose lines for folders the app itself writes; anything else gets a TODO.
fn purpose(folder: &str) -> &'static str {
    let name = folder.rsplit('/').next().unwrap_or(folder);
    match name.to_ascii_lowercase().as_str() {
        "output" => "generated output root — machine-written; canonical notes live outside it",
        "meetings" => "meeting notes (transcript + summary + action items)",
        "briefs" => "morning briefs",
        "people" => "per-person pages (actions + meetings), rebuilt automatically",
        "memory" => "durable memory notes from the nightly harvest",
        "reviews" => "weekly reviews and curation reports",
        "codex" => "book highlights and reading notes from CipherCodex",
        _ => "(document what belongs here)",
    }
}

/// Path-like tokens in a contract: backtick-quoted spans and bare tokens
/// containing '/'. Normalized: backslashes -> '/', trailing '/' trimmed,
/// lowercased for comparison. std-only — no regex dependency.
fn routes(text: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut push = |tok: &str| {
        let t = tok
            .replace('\\', "/")
            .trim()
            .trim_matches('`')
            .trim_end_matches('/')
            .to_lowercase();
        // Callers already require the pre-trim token to contain '/' (or
        // '\\'); re-checking post-trim here drops single-segment routes
        // like `output/` (trims to "output", no interior slash).
        // Tokens containing ':' are URLs (https://...) or Windows absolute
        // paths (C:\...) — never vault-relative folder routes.
        if !t.is_empty() && !t.contains(':') {
            out.insert(t);
        }
    };
    // Backtick spans.
    let mut rest = text;
    while let Some(start) = rest.find('`') {
        let after = &rest[start + 1..];
        let Some(end) = after.find('`') else { break };
        let span = &after[..end];
        if span.contains('/') || span.contains('\\') {
            push(span);
        }
        rest = &after[end + 1..];
    }
    // Bare tokens with a slash (e.g. "notes go to output/meetings/").
    for tok in text.split_whitespace() {
        let t = tok.trim_matches(|c: char| !c.is_alphanumeric() && c != '/' && c != '\\' && c != '.' && c != '-' && c != '_');
        if t.contains('/') && !t.contains("://") {
            push(t);
        }
    }
    out
}

fn route_matches_folder(route: &str, folders_lower: &BTreeSet<String>) -> bool {
    folders_lower.contains(route)
        || folders_lower.iter().any(|f| f.starts_with(&format!("{route}/")))
}

fn folder_documented(folder_lower: &str, all_routes: &BTreeSet<String>) -> bool {
    all_routes.contains(folder_lower)
        || all_routes.iter().any(|r| folder_lower.starts_with(&format!("{r}/")))
}

pub fn diagnose(contracts: &[(String, String)], folders: &[String]) -> DoctorReport {
    let folders_lower: BTreeSet<String> = folders.iter().map(|f| f.to_lowercase()).collect();
    let mut findings: Vec<DoctorFinding> = Vec::new();
    let mut patch_lines: Vec<String> = Vec::new();

    if contracts.is_empty() {
        findings.push(DoctorFinding {
            kind: "no-contract".into(),
            detail: "No CLAUDE.md or AGENTS.md in the vault — agents have no routing contract.".into(),
        });
        // Bootstrap: document every real folder + propose missing destinations.
        let mut doc = String::from(
            "# Vault memory contract\n\nWhere things live and where new output belongs. Generated by cipherManager's\nContract Doctor from the actual folder layout — edit the purpose lines to match reality.\n\n## Routes\n\n",
        );
        for f in folders {
            doc.push_str(&format!("- `{f}/` — {}\n", purpose(f)));
        }
        let mut missing: Vec<&str> = Vec::new();
        for cat in CATEGORIES {
            if !folders_lower.iter().any(|f| f.contains(cat)) {
                missing.push(cat);
            }
        }
        if !missing.is_empty() {
            doc.push_str("\n## Proposed new routes\n\n");
            for cat in &missing {
                doc.push_str(&format!("- {cat}: no home yet — decide where {cat} notes land and add a route above.\n"));
                findings.push(DoctorFinding {
                    kind: "missing-destination".into(),
                    detail: format!("No folder or route for {cat}."),
                });
            }
        }
        return DoctorReport { contract_rel: None, findings, patch: Some(doc), healthy: false };
    }

    let contract_rel = Some(contracts[0].0.clone());
    let per_contract: Vec<(String, BTreeSet<String>)> =
        contracts.iter().map(|(n, t)| (n.clone(), routes(t))).collect();
    let all_routes: BTreeSet<String> = per_contract.iter().flat_map(|(_, r)| r.iter().cloned()).collect();
    let all_text_lower: String = contracts.iter().map(|(_, t)| t.to_lowercase()).collect();

    for r in &all_routes {
        if !route_matches_folder(r, &folders_lower) {
            findings.push(DoctorFinding {
                kind: "dead-route".into(),
                detail: format!("Contract references `{r}/` but no such folder exists."),
            });
        }
    }
    for f in folders {
        if !folder_documented(&f.to_lowercase(), &all_routes) {
            findings.push(DoctorFinding {
                kind: "undocumented-folder".into(),
                detail: format!("Folder `{f}/` exists but the contract never mentions it."),
            });
            patch_lines.push(format!("- `{f}/` — {}", purpose(f)));
        }
    }
    for cat in CATEGORIES {
        let in_routes = all_routes.iter().any(|r| r.contains(cat));
        let in_text = all_text_lower.contains(cat);
        if !in_routes && !in_text {
            findings.push(DoctorFinding {
                kind: "missing-destination".into(),
                detail: format!("No route or mention says where {cat} belong."),
            });
            patch_lines.push(format!("- {cat}: (decide where these land and document the route)"));
        }
    }
    if per_contract.len() > 1 {
        for cat in CATEGORIES {
            let sets: Vec<(&str, BTreeSet<&String>)> = per_contract
                .iter()
                .map(|(n, r)| (n.as_str(), r.iter().filter(|x| x.contains(cat)).collect()))
                .collect();
            let non_empty: Vec<&(&str, BTreeSet<&String>)> =
                sets.iter().filter(|(_, s)| !s.is_empty()).collect();
            if non_empty.len() > 1 && non_empty.windows(2).any(|w| w[0].1 != w[1].1) {
                findings.push(DoctorFinding {
                    kind: "conflict".into(),
                    detail: format!(
                        "CLAUDE.md and AGENTS.md give different routes for {cat}: {}",
                        non_empty
                            .iter()
                            .map(|(n, s)| format!("{n}: {}", s.iter().map(|x| x.as_str()).collect::<Vec<_>>().join(", ")))
                            .collect::<Vec<_>>()
                            .join(" vs ")
                    ),
                });
            }
        }
    }
    if folders_lower.iter().any(|f| f.contains("output")) && !all_text_lower.contains("generat") {
        findings.push(DoctorFinding {
            kind: "no-generated-rule".into(),
            detail: "An output/ folder exists but the contract never states what is generated vs canonical.".into(),
        });
        patch_lines.push("- `output/` holds generated files; canonical, hand-maintained notes live outside it.".into());
    }

    let patch = if patch_lines.is_empty() {
        None
    } else {
        Some(format!(
            "\n## Memory contract additions (proposed by Contract Doctor)\n\n{}\n",
            patch_lines.join("\n")
        ))
    };
    let healthy = findings.is_empty();
    DoctorReport { contract_rel, findings, patch, healthy }
}

/// Read the vault's contract files and folder layout (depth ≤ 2, hidden dirs
/// skipped), confined to the canonicalized vault dir.
pub fn vault_doctor_impl(dir: &str) -> Result<DoctorReport, String> {
    let base = Path::new(dir)
        .canonicalize()
        .map_err(|_| format!("vault folder not found: {dir}"))?;
    let mut contracts: Vec<(String, String)> = Vec::new();
    for name in ["CLAUDE.md", "AGENTS.md"] {
        let p = base.join(name);
        if let Ok(t) = std::fs::read_to_string(&p) {
            contracts.push((name.to_string(), t));
        }
    }
    let mut folders: Vec<String> = Vec::new();
    let level = |p: &Path, prefix: &str, out: &mut Vec<String>| -> Vec<std::path::PathBuf> {
        let mut subs = Vec::new();
        if let Ok(rd) = std::fs::read_dir(p) {
            for e in rd.flatten() {
                let Ok(ft) = e.file_type() else { continue };
                if !ft.is_dir() {
                    continue;
                }
                let name = e.file_name().to_string_lossy().to_string();
                if name.starts_with('.') {
                    continue;
                }
                out.push(if prefix.is_empty() { name.clone() } else { format!("{prefix}/{name}") });
                subs.push(e.path());
            }
        }
        subs
    };
    let top = level(&base, "", &mut folders);
    // Capture top-level names before the second loop pushes depth-2 folders,
    // then zip rather than index into `folders` (which keeps growing).
    let top_names: Vec<String> = folders.clone();
    for (sub, prefix) in top.iter().zip(top_names) {
        level(sub, &prefix, &mut folders);
    }
    folders.sort();
    Ok(diagnose(&contracts, &folders))
}

#[tauri::command]
pub async fn vault_doctor(dir: String) -> Result<DoctorReport, String> {
    tauri::async_runtime::spawn_blocking(move || vault_doctor_impl(&dir))
        .await
        .map_err(|e| e.to_string())?
}

#[cfg(test)]
mod tests {
    use super::*;

    fn folders() -> Vec<String> {
        ["output", "output/meetings", "output/briefs", "output/people"]
            .iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn no_contract_bootstraps_a_full_patch() {
        let r = diagnose(&[], &folders());
        assert!(!r.healthy);
        assert_eq!(r.contract_rel, None);
        assert!(r.findings.iter().any(|f| f.kind == "no-contract"));
        let patch = r.patch.expect("bootstrap patch");
        // Documents every real folder and proposes the missing destinations.
        assert!(patch.contains("`output/meetings/`"));
        assert!(patch.contains("`output/people/`"));
        assert!(patch.contains("decisions"));
        // Deterministic: same inputs, same bytes.
        assert_eq!(diagnose(&[], &folders()).patch.unwrap(), patch);
    }

    #[test]
    fn healthy_contract_reports_no_changes() {
        let contract = "# Contract\n\n- `output/` — generated output only; canonical notes live elsewhere.\n- `output/meetings/` — meeting notes\n- `output/briefs/` — daily briefs\n- `output/people/` — people pages\n- decisions land in `output/meetings/`\n- projects context lives in `output/briefs/`\n- memory notes land in `output/meetings/`\n";
        let r = diagnose(&[("CLAUDE.md".into(), contract.into())], &folders());
        assert!(r.healthy, "unexpected findings: {:?}", r.findings);
        assert_eq!(r.patch, None);
        assert_eq!(r.contract_rel.as_deref(), Some("CLAUDE.md"));
    }

    #[test]
    fn drift_findings_dead_route_undocumented_and_missing_destination() {
        let contract = "- `output/meetings/` — meeting notes\n- `output/ghost/` — does not exist\n";
        let r = diagnose(&[("CLAUDE.md".into(), contract.into())], &folders());
        let kinds: Vec<&str> = r.findings.iter().map(|f| f.kind.as_str()).collect();
        assert!(kinds.contains(&"dead-route"), "{kinds:?}");          // output/ghost documented, absent
        assert!(kinds.contains(&"undocumented-folder"), "{kinds:?}"); // output/briefs, output/people exist, unmentioned
        assert!(kinds.contains(&"missing-destination"), "{kinds:?}"); // no route for decisions/projects/…
        assert!(kinds.contains(&"no-generated-rule"), "{kinds:?}");   // contract never says what's generated vs canonical
        let patch = r.patch.expect("drift patch");
        assert!(patch.contains("`output/briefs/`"));
        assert!(!patch.contains("# Vault memory contract"), "drift patch must be an addition, not a bootstrap");
    }

    #[test]
    fn conflicting_contracts_flag_per_category() {
        let a = "- meetings notes go to `output/meetings/`\n";
        let b = "- meeting notes go to `notes/meetings/`\n";
        let r = diagnose(
            &[("CLAUDE.md".into(), a.into()), ("AGENTS.md".into(), b.into())],
            &["output".into(), "output/meetings".into(), "notes".into(), "notes/meetings".into()],
        );
        assert!(r.findings.iter().any(|f| f.kind == "conflict" && f.detail.contains("meetings")));
    }

    #[test]
    fn route_extraction_handles_backticks_and_trailing_slashes() {
        let routes = routes(
            "see `output/meetings/` and also `output\\briefs` plus plain text, \
             but not `https://example.com/docs` or `C:\\Users\\x\\Documents`",
        );
        assert!(routes.contains("output/meetings"));
        assert!(routes.contains("output/briefs"));
        assert!(!routes.iter().any(|r| r.contains("example.com")));
        assert!(!routes.iter().any(|r| r.contains("users/x/documents")));
        assert_eq!(routes.len(), 2);
    }
}
